name: Spring Boot CI/CD

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:

      # 1. Get source code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Build Spring Boot application
      - name: Build application
        run: |
          chmod +x mvnw
          ./mvnw clean package -DskipTests

      # 3. Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 4. Login to ECR
      - name: Login to ECR
        run: |
          aws ecr get-login-password --region eu-north-1 |
          docker login --username AWS --password-stdin \
          202029085969.dkr.ecr.eu-north-1.amazonaws.com

      # 5. Build Docker image
      - name: Build Docker image
        run: |
          docker build \
            -t 202029085969.dkr.ecr.eu-north-1.amazonaws.com/spring-app:${{ github.sha }} .

      # 6. Push Docker image to ECR
      - name: Push Docker image
        run: |
          docker push \
            202029085969.dkr.ecr.eu-north-1.amazonaws.com/spring-app:${{ github.sha }}

      # 7. Get current ECS task definition
      - name: Get ECS task definition
        run: |
          aws ecs describe-task-definition \
            --task-definition spring-task \
            --region eu-north-1 \
            --query taskDefinition \
            --output json > task-definition.json

          jq 'del(
            .taskDefinitionArn,
            .revision,
            .status,
            .requiresAttributes,
            .compatibilities,
            .registeredAt,
            .registeredBy
          )' task-definition.json > task-definition-clean.json

      # 8. Update container image in task definition
      - name: Update ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition-clean.json
          container-name: spring-container
          image: 202029085969.dkr.ecr.eu-north-1.amazonaws.com/spring-app:${{ github.sha }}

      # 9. Deploy new task definition to ECS
      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: spring-service
          cluster: spring-cluster
          wait-for-service-stability: true
